version: '3.8'

services:
  cyclestore:
    build: .
    expose:
      - "8000"
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-this}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./app/static/images:/app/app/static/images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./app/static:/var/www/static:ro
    depends_on:
      - cyclestore
    restart: unless-stopped

volumes:
  cyclestore_data:
